force-app/main/default/objects/Account/fields/SFTrainingCount__c.field-meta.xml
<CustomField>
    <fullName>SFTrainingCount__c</fullName>
    <label>SFトレーニング参加人数</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/M_SFTraining__c/M_SFTraining__c.object-meta.xml
<CustomObject>
    <label>SFトレーニング</label>
    <nameField>
        <label>参加コース</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/M_SFTraining__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>参加者</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SFトレーニング</relationshipLabel>
    <relationshipName>attendee</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/M_SFTraining__c/fields/ParticipationDate__c.field-meta.xml
<CustomField>
    <fullName>ParticipationDate__c</fullName>
    <label>参加日</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CL_Test_SFTraining.cls
@isTest
public class CL_Test_SFTraining {
    //同じ取引先の取先責任者が2件作成
    @testSetup static void setup(){   
        Account acc = new Account(
            Name = 'TestAcc' 
        );   
        insert acc;
        
        List<Contact> cons = new List<Contact>();
        Contact con1 = new Contact(
            LastName = 'TestCon1',
            AccountId=acc.id
        );   
        cons.add(con1);
        Contact con2 = new Contact(
            LastName = 'TestCon2',
            AccountId=acc.id
        );   
        cons.add(con2);
        insert cons;
    }
    
    
    @isTest static void test0001_positive() {
        // 同じ取引先の2名の取先責任者はそれぞれトレーニングレコードが１件づつ作成
        List<Contact> cons  = [SELECT Id,AccountId,LastName FROM Contact ];
        List<M_SFTraining__c> trs = new List<M_SFTraining__c>(); 
        
        M_SFTraining__c tr1 = new M_SFTraining__c(
            Name = 'SF1',
            Participant__c=cons[0].id,
            ParticipationDate__c = date.today()  
        );
        trs.add(tr1);
        M_SFTraining__c tr2 = new M_SFTraining__c(
            Name = 'SF2',
            Participant__c=cons[1].id,
            ParticipationDate__c = date.today()  
        );
        trs.add(tr2);
        
        // テスト開始
        Test.startTest();
        Database.SaveResult[] results = Database.insert(trs, false);  
        Test.stopTest();
        
        // 検証       
        ACCOUNT acc = [SELECT  Name,SFTrainingCount__c  FROM ACCOUNT    WHERE name='TestAcc' LIMIT 1];
        // 取引先別の参加人数は2名であること
        Assert.areEqual(2, acc.SFTrainingCount__c);
    }
}